/*
 * actions.ts -- the four things that travel as actions.
 *
 * Copyright (C) 2026 queep-3-arena contributors
 *
 * This program is free software; you can redistribute it and/or modify it under
 * the terms of the GNU General Public License as published by the Free Software
 * Foundation; either version 2 of the License, or (at your option) any later
 * version. See LICENSE.
 *
 * ---
 *
 * A `SimAction` is the only legal mutator of replicated state, and there are
 * exactly two kinds of them here.
 *
 * **`UserCmdAction` mutates.** It names a slot and a frame and carries one
 * `usercmd_t`; applying it runs that slot's shared per-frame step. It declares
 * the slot's `NetPlayerState` and `NetInventory` as affected, so the executor
 * captures their prior bytes and a rewind can put them back -- which is the
 * whole reason the shared step's *entire* carried state has to live in those
 * two components (see `components.ts`).
 *
 * **The other three do not mutate anything**, and that is a load-bearing
 * property rather than a simplification. An action with no affected components
 * is one the `Replicator` always sends, the `RewindEngine` never touches, and
 * the receiving executor applies exactly once. So a muzzle flash cannot be
 * un-fired by a rollback, and cannot be fired twice by a retransmission. They
 * are the wire form of `WeaponEvents`, and on the host their `apply` does
 * nothing at all: the host raised the event that created them in the first
 * place.
 *
 * **Every class here is built per session by a factory**, which is the engine's
 * own pattern -- `NetworkSession.#make_replace_component_action_class` does
 * exactly this. `SimActionRegistry.register` writes `static type_id` onto the
 * class, so a class shared between two sessions in one process (which is every
 * test in `test/net/`) would have its id overwritten by whichever session
 * started last. The factory also gives `apply` a way to reach this peer's game
 * objects without a module-level global.
 *
 * `serialize`/`deserialize` are hand-written rather than generated by
 * `SimAction.extend`, because `extend`'s schema has integer, float and string
 * types and no array type, and half of a `usercmd_t` is arrays.
 */

import { SimAction } from '@woosh/meep-engine/src/engine/network/sim/SimAction.js';
import type { BinaryBuffer } from '@woosh/meep-engine/src/core/binary/BinaryBuffer.js';

import { createUserCmd, type UserCmd } from '../q3/pmove/types.ts';

/* ------------------------------------------------------------------ *
 * What a peer has to supply for these to mean anything
 * ------------------------------------------------------------------ */

/**
 * The seam between a wire action and this peer's game objects.
 *
 * The host implements all of it; a client implements `stepSlot` for its own
 * slot and the three event handlers, and answers `false` from `simulates` for
 * every other slot -- the host relays every client's commands to every other
 * client, and a client that simulated one would be running a second, unowned
 * copy of somebody else's player against its own predicted world.
 */
export interface ActionContext {
    /**
     * Run the shared per-frame step for the slot living on `entity`.
     *
     * The implementation loads the slot's state out of its replicated
     * components, steps, and writes them back -- so a rewind that rewrote those
     * components is a complete description of where to replay from.
     */
    stepSlot(entity: number, cmd: UserCmd, frame: number): void;

    /** Whether this peer simulates the slot on `entity` at all. */
    simulates(entity: number): boolean;

    /** A transient happening arrived. No-op on the host, which raised it. */
    effect(event: EffectEventData): void;
    hit(event: HitEventData): void;
    pickup(event: PickupEventData): void;
    /**
     * A player has gone; destroy the entity that was them.
     *
     * No-op on the host, which raised it, and on a client that never heard of
     * the id -- which is the ordinary case for a player who joined and left
     * between two of this client's snapshots.
     */
    playerLeft(event: PlayerLeftData): void;
}

/** The five shapes `WeaponEvents` raises, as one byte. */
export const EffectKind = Object.freeze({
    MuzzleFlash: 0,
    HitscanTrail: 1,
    BulletImpact: 2,
    Explosion: 3,
    Death: 4,
});

/**
 * The `owner` a happening the world caused carries.
 *
 * `EffectEventData.owner` and `HitEventData.attacker` are both slot indices in a
 * byte, and both need a value for "nobody did this": a rocket that hits a wall,
 * a `trigger_hurt` that burns a player who walked into it. 255 rather than -1
 * so it survives the `uint8` on the wire, and named rather than spelled out at
 * each site so that grepping for the world's damage finds all of it.
 */
export const WORLD_OWNER = 255;

/**
 * One transient effect.
 *
 * `aux` is the second vector each kind needs and they are not the same vector:
 * a direction for a muzzle flash, a surface normal for an impact or an
 * explosion, the far end for a trail. One field rather than three because the
 * kinds are mutually exclusive and a union on the wire is three unused floats
 * per event on every other kind.
 */
export interface EffectEventData {
    kind: number;
    /** Index into `NET_WEAPONS`. */
    weapon: number;
    /** The slot that caused it, or 255 for the world. */
    owner: number;
    origin: Float32Array;
    aux: Float32Array;
    /** Blast radius for an explosion; zero elsewhere. */
    radius: number;
}

export interface HitEventData {
    attacker: number;
    victim: number;
    damage: number;
}

export interface PickupEventData {
    slot: number;
    /** `ItemInstance.index`, which both peers loaded from the same map. */
    item: number;
}

/**
 * A player has gone, and the entity that was them should go with it.
 *
 * **This action exists because removal is the one direction replication does
 * not go.** A host that creates an entity mid-match can teach a connected
 * client about it by pushing a fresh INITIAL_SYNC -- measured, and the engine's
 * own `#apply_initial_sync` handles the already-allocated case on purpose. A
 * host that *destroys* one cannot: there is no CREATE or DESTROY among the
 * thirteen `NetworkPacketType`s, and a snapshot only creates entities the
 * receiver does not know, so a client that has an entity the snapshot omits
 * keeps it. Measured on 3.15.0: after the host destroyed the entity and pushed
 * a snapshot, the client still held it.
 *
 * So the reap is the application's. The host says which network id has gone and
 * the client destroys its own copy, which it is entitled to do because it owns
 * its local entities. See GAP-038 and D-194.
 */
export interface PlayerLeftData {
    /** The `network_id` of the entity to destroy, not a game-level player id. */
    networkId: number;
    /** The game-level id that has been freed, for the roster. */
    playerId: number;
}

/** What {@link makeActions} hands back. The array order is the wire order. */
export interface ProtocolActions {
    UserCmdAction: UserCmdActionClass;
    EffectEvent: EffectEventClass;
    HitEvent: HitEventClass;
    PickupEvent: PickupEventClass;
    PlayerLeft: PlayerLeftClass;
    /** In `defineAction` order, which must be identical on every peer. */
    all: readonly Function[];
}

export interface UserCmdActionInstance extends SimAction {
    networkId: number;
    frame: number;
    readonly cmd: UserCmd;
    set(networkId: number, frame: number, cmd: UserCmd): void;
}

export interface EffectEventInstance extends SimAction, EffectEventData {}
export interface HitEventInstance extends SimAction, HitEventData {}
export interface PickupEventInstance extends SimAction, PickupEventData {}
export interface PlayerLeftInstance extends SimAction, PlayerLeftData {}

type UserCmdActionClass = new () => UserCmdActionInstance;
type EffectEventClass = new () => EffectEventInstance;
type HitEventClass = new () => HitEventInstance;
type PickupEventClass = new () => PickupEventInstance;
type PlayerLeftClass = new () => PlayerLeftInstance;

/**
 * `SimActionExecutor`, as much of it as an action touches. The engine types the
 * parameter as the whole executor; an action needs one method off it.
 */
interface ExecutorLike {
    slot_table: { entity_for(networkId: number): number };
}

/**
 * The two components a `UserCmdAction` may write. Passed in rather than
 * imported so this module never decides the protocol's shape -- `registerProtocol`
 * does, in one place.
 */
export interface SteppedComponents {
    state: Function;
    inventory: Function;
}

/**
 * Build this session's action classes.
 *
 * @param ctx how the actions reach this peer's game objects
 * @param stepped the components a `UserCmdAction` declares as affected
 */
export function makeActions(ctx: ActionContext, stepped: SteppedComponents): ProtocolActions {
    /**
     * One player's input for one frame.
     *
     * The frame number is on the wire and is not the frame the packet arrived
     * in: the host defers the action and applies it at *its* frame, rewinding
     * if it has already passed. That is the whole of what makes a client's
     * prediction and the host's authority describe the same simulation.
     */
    class UserCmdAction extends SimAction implements UserCmdActionInstance {
        networkId = 0;
        frame = 0;
        readonly cmd: UserCmd = createUserCmd();

        set(networkId: number, frame: number, cmd: UserCmd): void {
            this.networkId = networkId;
            this.frame = frame;
            this.cmd.serverTime = cmd.serverTime;
            this.cmd.angles.set(cmd.angles);
            this.cmd.moves.set(cmd.moves);
            this.cmd.buttons = cmd.buttons;
            this.cmd.weapon = cmd.weapon;
        }

        override apply(_world: unknown, executor: ExecutorLike): void {
            const entity = executor.slot_table.entity_for(this.networkId);
            if (entity < 0) return;
            if (!ctx.simulates(entity)) return;
            ctx.stepSlot(entity, this.cmd, this.frame);
        }

        override affected_components(
            callback: (entity: number, component: Function) => void,
            executor: ExecutorLike
        ): void {
            const entity = executor.slot_table.entity_for(this.networkId);
            if (entity < 0) return;
            callback(entity, stepped.state);
            callback(entity, stepped.inventory);
        }

        override serialize(buffer: BinaryBuffer): void {
            buffer.writeUintVar(this.networkId);
            buffer.writeUintVar(this.frame);
            buffer.writeInt16(this.cmd.angles[0]!);
            buffer.writeInt16(this.cmd.angles[1]!);
            buffer.writeInt16(this.cmd.angles[2]!);
            buffer.writeInt8(this.cmd.moves[0]!);
            buffer.writeInt8(this.cmd.moves[1]!);
            buffer.writeInt8(this.cmd.moves[2]!);
            buffer.writeUint8(this.cmd.buttons);
            buffer.writeUint8(this.cmd.weapon);
        }

        override deserialize(buffer: BinaryBuffer): void {
            this.networkId = buffer.readUintVar();
            this.frame = buffer.readUintVar();
            this.cmd.angles[0] = buffer.readInt16();
            this.cmd.angles[1] = buffer.readInt16();
            this.cmd.angles[2] = buffer.readInt16();
            this.cmd.moves[0] = buffer.readInt8();
            this.cmd.moves[1] = buffer.readInt8();
            this.cmd.moves[2] = buffer.readInt8();
            this.cmd.buttons = buffer.readUint8();
            this.cmd.weapon = buffer.readUint8();
            /*
             `serverTime` is deliberately not on the wire. It is `frameMsec`
             summed to this frame, which both peers compute from `frame`; two
             machines that disagreed about it would be running the same command
             on two different clocks, and sending it would let a client choose
             the host's.
            */
            this.cmd.serverTime = 0;
        }

        override reset(): void {
            this.networkId = 0;
            this.frame = 0;
            this.cmd.serverTime = 0;
            this.cmd.angles.fill(0);
            this.cmd.moves.fill(0);
            this.cmd.buttons = 0;
            this.cmd.weapon = 0;
        }
    }

    class EffectEvent extends SimAction implements EffectEventInstance {
        kind = 0;
        weapon = 0;
        owner = 0;
        readonly origin = new Float32Array(3);
        readonly aux = new Float32Array(3);
        radius = 0;

        override apply(): void {
            ctx.effect(this);
        }

        override serialize(buffer: BinaryBuffer): void {
            buffer.writeUint8(this.kind);
            buffer.writeUint8(this.weapon);
            buffer.writeUint8(this.owner);
            buffer.writeFloat32(this.origin[0]!);
            buffer.writeFloat32(this.origin[1]!);
            buffer.writeFloat32(this.origin[2]!);
            buffer.writeFloat32(this.aux[0]!);
            buffer.writeFloat32(this.aux[1]!);
            buffer.writeFloat32(this.aux[2]!);
            buffer.writeFloat32(this.radius);
        }

        override deserialize(buffer: BinaryBuffer): void {
            this.kind = buffer.readUint8();
            this.weapon = buffer.readUint8();
            this.owner = buffer.readUint8();
            this.origin[0] = buffer.readFloat32();
            this.origin[1] = buffer.readFloat32();
            this.origin[2] = buffer.readFloat32();
            this.aux[0] = buffer.readFloat32();
            this.aux[1] = buffer.readFloat32();
            this.aux[2] = buffer.readFloat32();
            this.radius = buffer.readFloat32();
        }

        override reset(): void {
            this.kind = 0;
            this.weapon = 0;
            this.owner = 0;
            this.origin.fill(0);
            this.aux.fill(0);
            this.radius = 0;
        }
    }

    class HitEvent extends SimAction implements HitEventInstance {
        attacker = 0;
        victim = 0;
        damage = 0;

        override apply(): void {
            ctx.hit(this);
        }

        override serialize(buffer: BinaryBuffer): void {
            buffer.writeUint8(this.attacker);
            buffer.writeUint8(this.victim);
            buffer.writeUint8(this.damage);
        }

        override deserialize(buffer: BinaryBuffer): void {
            this.attacker = buffer.readUint8();
            this.victim = buffer.readUint8();
            this.damage = buffer.readUint8();
        }

        override reset(): void {
            this.attacker = 0;
            this.victim = 0;
            this.damage = 0;
        }
    }

    class PickupEvent extends SimAction implements PickupEventInstance {
        slot = 0;
        item = 0;

        override apply(): void {
            ctx.pickup(this);
        }

        override serialize(buffer: BinaryBuffer): void {
            buffer.writeUint8(this.slot);
            buffer.writeUint16(this.item);
        }

        override deserialize(buffer: BinaryBuffer): void {
            this.slot = buffer.readUint8();
            this.item = buffer.readUint16();
        }

        override reset(): void {
            this.slot = 0;
            this.item = 0;
        }
    }

    /**
     * A player has gone. Appended to the action list rather than inserted, so
     * every action before it keeps its type id and a peer built against the
     * older protocol disagrees about one id rather than about all of them.
     */
    class PlayerLeft extends SimAction implements PlayerLeftInstance {
        networkId = 0;
        playerId = 0;

        override apply(): void {
            ctx.playerLeft(this);
        }

        override serialize(buffer: BinaryBuffer): void {
            buffer.writeUintVar(this.networkId);
            buffer.writeUint8(this.playerId);
        }

        override deserialize(buffer: BinaryBuffer): void {
            this.networkId = buffer.readUintVar();
            this.playerId = buffer.readUint8();
        }

        override reset(): void {
            this.networkId = 0;
            this.playerId = 0;
        }
    }

    return {
        UserCmdAction,
        EffectEvent,
        HitEvent,
        PickupEvent,
        PlayerLeft,
        all: [UserCmdAction, EffectEvent, HitEvent, PickupEvent, PlayerLeft],
    };
}

/**
 * A context that does nothing, for a peer that has no game objects yet.
 *
 * Used by `test/net-protocol.test.ts`, which is about the wire format and not
 * about the simulation, and by any peer constructing a session before its world
 * exists.
 */
export const INERT_CONTEXT: ActionContext = {
    stepSlot() {},
    simulates() {
        return false;
    },
    effect() {},
    hit() {},
    pickup() {},
    playerLeft() {},
};
